# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db9314778d3681ccc26c40e0809be128f046d4ce7200e2de35c57f93a14a4ab2d540aa5837bd3a49b3029e08c2e8737290a3316cbec120de9740bcb6c342ade6

test:
  secret_key_base: 608f18abfa39f1a99b5a7be6847ed546e2357113fab2969cb63256b09488949a72d4930cfc0f853a35d29cb2fc1008a1b451043013eb4ed925465970a8cdbf0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
